net:
    G: edsr8
    P: conv4

    edsr8:
        type: SimpleResnet
        channel: 64
        bottleneck: False
        block_num: 8
        layer:
            conv:
                kernel: 3
                stride: 1
                pad:    1
                weight_filler: "msra"

    conv4:
        type: SimpleCNN 
        conv_num: 3
        channel: 64
        channel_plus: 2
        map_size: 7
        layer:
            conv:
                kernel: 3
                stride: 2
                pad:    1
                weight_filler: "xavier"
            scale:
                param: 
                    - lr_mult: 1
                    - lr_mult: 0.01
data:
    batch_size: 10
    prefix: /data3/lzh/10000x10x224x224_ring_colored_diff_filtered/

loss:
    RefLoss: True
    MSELoss: True
